__main__:102:INFO (<module>) - Dynamite's logger_level: DEBUG
__main__:103:INFO (<module>) - Dig's logger_level: WARNING
__main__:104:INFO (<module>) - Timeout: 900s
__main__:106:INFO (<module>) - 2020-05-14 23:30:33.318824: dynamo.py --timeout=900 /home/exp/eric/dynamo/benchmarks/nla-term/freire1-both-t.c
/home/exp/tools/SageMath/local/lib/python3.7/site-packages/pyximport/pyximport.py:51: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
analysis:72:DEBUG (__init__) - Create C source for mainQ: /var/tmp/Dig_74mdfdtq
analysis:80:DEBUG (__init__) - trans_cmd: /home/exp/eric/dynamo/deps/dynamo-instr/src/cil/bin/cilly --save-temps -D HAPPY_MOOD --dotransform /home/exp/eric/dynamo/benchmarks/nla-term/freire1-both-t.c --out=/var/tmp/Dig_74mdfdtq/freire1-both-t.c --bnd=500
analysis:87:DEBUG (__init__) - cg: defaultdict(<class 'list'>, {'vloop_32': ['exit'], 'mainQ': ['vloop_32'], 'main': ['mainQ']})
analysis:98:DEBUG (__init__) - postorder_vloop_ids: ['vloop_32']
analysis:107:DEBUG (__init__) - inp_decls (<class 'data.prog.Symbs'>): I a, I k
analysis:108:DEBUG (__init__) - inv_decls (<class 'data.prog.DSymbs'>): {'vtrace1_32': (Symb(name='r', typ='I'), Symb(name='x', typ='I'), Symb(name='a', typ='I'), Symb(name='c', typ='I'), Symb(name='k', typ='I')), 'vtrace2_32': (Symb(name='r', typ='I'), Symb(name='x', typ='I'), Symb(name='a', typ='I'), Symb(name='c', typ='I'), Symb(name='k', typ='I')), 'vtrace3_32': (Symb(name='r', typ='I'), Symb(name='x', typ='I'), Symb(name='a', typ='I'), Symb(name='c', typ='I'), Symb(name='k', typ='I'))}
__main__:152:DEBUG (<module>) - prove_process: 31961
lib:43:DEBUG (gen_rand_inps) - gen 107/100 random inps
utils.profiling:31:DEBUG (timed) - gen_rand_inps: 123.60ms
lib:54:DEBUG (get_traces_from_inps) - inp_decls: I a, I k
lib:55:DEBUG (get_traces_from_inps) - inv_decls: {'vtrace1_32': (Symb(name='r', typ='I'), Symb(name='x', typ='I'), Symb(name='a', typ='I'), Symb(name='c', typ='I'), Symb(name='k', typ='I')), 'vtrace2_32': (Symb(name='r', typ='I'), Symb(name='x', typ='I'), Symb(name='a', typ='I'), Symb(name='c', typ='I'), Symb(name='k', typ='I')), 'vtrace3_32': (Symb(name='r', typ='I'), Symb(name='x', typ='I'), Symb(name='a', typ='I'), Symb(name='c', typ='I'), Symb(name='k', typ='I'))}
utils.profiling:31:DEBUG (timed) - _get_traces_mp: 131.19ms
utils.profiling:31:DEBUG (timed) - _merge_traces: 243.07ms
utils.profiling:31:DEBUG (timed) - get_traces_from_inps: 374.79ms
analysis:1153:DEBUG (prove) - Analysing vloop_32
analysis:1155:DEBUG (prove) - base_term_inps: 52
analysis:1156:DEBUG (prove) - term_inps: 0
analysis:1157:DEBUG (prove) - mayloop_inps: 55
analysis:1179:DEBUG (prove) - Proving Termination: vloop_32
analysis:1046:DEBUG (prove_term_vloop) - classify_inps: vloop_32
analysis:1049:DEBUG (prove_term_vloop) - itraces: 0
analysis:1051:DEBUG (prove_term_vloop) - base_term_inps: 0
analysis:1052:DEBUG (prove_term_vloop) - term_inps: 0
analysis:1053:DEBUG (prove_term_vloop) - mayloop_inps: 0
analysis:863:DEBUG (infer_ranking_functions) - vloop: vloop_32
analysis:864:DEBUG (infer_ranking_functions) - term_itraces: 0
utils.profiling:31:DEBUG (timed) - infer_ranking_functions: 0.05ms
analysis:1067:DEBUG (prove_term_vloop) - validate_ranking_functions: vloop_32
analysis:994:DEBUG (validate_ranking_functions) - ranks_str: 
validate:123:DEBUG (gen_validate_file) - validate_cmd: /home/exp/eric/dynamo/deps/dynamo-instr/src/cil/bin/cilly --save-temps -D HAPPY_MOOD --dovalidate /home/exp/eric/dynamo/benchmarks/nla-term/freire1-both-t.c --out=/var/tmp/Dig_74mdfdtq/vloop_32/par/validate/freire1-both-t.c --pos=32 --ranks=""
validate:41:DEBUG (prove_reach) - pcmd: /home/exp/tools/CPAchecker-1.9-unix/scripts/cpa.sh -spec /home/exp/tools/reachability.prp -predicateAnalysis -setprop counterexample.export.compressWitness=false /var/tmp/Dig_74mdfdtq/vloop_32/par/validate/freire1-both-t.c
validate:41:DEBUG (prove_reach) - pcmd: /home/exp/tools/ultimate/releaseScripts/default/UAutomizer-linux/Ultimate.py --spec /home/exp/tools/reachability.prp --architecture 32bit --witness-dir /var/tmp/Dig_74mdfdtq/vloop_32/par/uatm --witness-name witness.graphml --file /var/tmp/Dig_74mdfdtq/vloop_32/par/validate/freire1-both-t.c
validate:41:DEBUG (prove_reach) - pcmd: /home/exp/tools/ultimate/releaseScripts/default/UTaipan-linux/Ultimate.py --spec /home/exp/tools/reachability.prp --architecture 32bit --witness-dir /var/tmp/Dig_74mdfdtq/vloop_32/par/utp --witness-name witness.graphml --file /var/tmp/Dig_74mdfdtq/vloop_32/par/validate/freire1-both-t.c
validate:46:DEBUG (prove_reach) - res: False
validate:61:DEBUG (validate_witness) - vcmd: /home/exp/tools/CPAchecker-1.9-unix/scripts/cpa.sh -spec /home/exp/tools/reachability.prp -witnessValidation -witness /var/tmp/Dig_74mdfdtq/vloop_32/par/cpa/output/Counterexample.1.graphml /var/tmp/Dig_74mdfdtq/vloop_32/par/validate/freire1-both-t.c
validate:49:DEBUG (prove_reach) - validate_witness: DONE
validate:50:DEBUG (prove_reach) - cex: None
validate:253:DEBUG (prove_reach) - wrs: [('cpa', (False, None))]
validate:256:DEBUG (prove_reach) - Got result firstly from cpa
utils.profiling:31:DEBUG (timed) - prove_reach: 3843.06ms
analysis:1007:DEBUG (validate_ranking_functions) - r: False
utils.profiling:31:DEBUG (timed) - validate_ranking_functions: 3974.25ms
analysis:1069:DEBUG (prove_term_vloop) - Termination result (vloop_32): False ([])
utils.profiling:31:DEBUG (timed) - prove_term_vloop: 3974.67ms
analysis:1187:DEBUG (prove) - Proving Non-Termination: vloop_32
analysis:239:DEBUG (_get_stem_from_symstates) - vloop.preloop_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 24
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 24
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 29
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 34
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 39
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 44
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 49
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 54
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 59
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 64
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 69
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 74
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 79
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 84
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 89
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 94
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 99
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 104
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 109
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 114
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 119
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 124
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 129
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 134
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 139
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 144
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 149
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 154
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 159
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 164
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 169
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 174
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 179
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 184
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 189
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 194
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 199
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 204
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 209
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 214
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 219
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 224
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 229
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 234
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 239
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 244
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 249
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 254
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 259
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 264
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 269
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 274
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 279
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 284
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 289
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 294
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 299
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 304
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 309
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 314
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 319
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 324
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 329
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 334
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 339
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 344
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 349
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 354
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 359
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 364
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 369
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 374
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 379
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 384
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 389
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 394
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 399
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 404
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 409
data.symstates:63:ERROR (parse) - Cannot obtain symstates from '/var/tmp/Dig_74mdfdtq/symexe/freire1-both-t_mainQ.c.mainQ_410.straces'
data.symstates:63:ERROR (parse) - Cannot obtain symstates from '/var/tmp/Dig_74mdfdtq/symexe/freire1-both-t_mainQ.c.mainQ_413.straces'
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 414
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 419
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 424
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 429
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 434
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 439
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 444
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 449
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 454
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 459
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 464
data.symstates:317:WARNING (compute) - cannot obtain symbolic states, unreachable locs?
analysis:194:DEBUG (_get_symstates_from_src) - Traceback (most recent call last):
  File "/home/exp/eric/dynamo/src/analysis.py", line 192, in _get_symstates_from_src
    symstates.compute(src.symexefile, src.mainQ_name, src.funname, src.symexedir)
  File "/home/exp/eric/dynamo/deps/dig/src/data/symstates.py", line 319, in compute
    sys.exit(0)
SystemExit: 0

analysis:197:DEBUG (_get_symstates_from_src) - target_loc: vtrace1_32
analysis:184:DEBUG (_get_symstates_from_src) - SymStatesC.maxdepth: 469

EJK TIMER: 900.000232

